version: '3'

services:
  gateway:
    build: ./
    container_name: e-commerce_gateway
    command: |
      sh -c "uvicorn --host 0.0.0.0 --port 8000 --reload src.main:app"
    volumes:
      - ./:/usr/src/app/
      - ../proto/:/usr/src/app/proto/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
